#' @name constants
#' @title Constants for Use in the redcapAPI Package
#'
#' @description Constants that are used inside the package
#'

# The field names listed here are those generated by REDCap. 
# A listing of these fields was needed to support missingSummary.
# It wouldn't hurt to contemplate how these could be obtained 
# dynamically rather than relying up updating constants.

#' @export

REDCAP_SYSTEM_FIELDS <- c("redcap_event_name", 
                          "redcap_data_access_group", 
                          "redcap_repeat_instrument", 
                          "redcap_repeat_instance")