#' @name deleteArms
#' @title Delete Arms From a Project
#' 
#' @description Delete arms from a project.  This is a destructive action that
#'   will result in deletion of any events and data associated with the arm.
#'   Due to its destructive nature, it may only be performed on databases 
#'   in development status.  Data loss is non-reversible.
#'   
#' @param rcon A REDCap connection object as generated by 
#'   \code{redcapConnection}.
#' @param arms \code{integerish(1)}, the arm number of the arm in which the 
#'   record(s) should be deleted. (This can only be used if the project is 
#'   longitudinal with more than one arm.) NOTE: If the arm parameter is not 
#'   provided, the specified records will be deleted from all arms in which 
#'   they exist. Whereas, if arm is provided, they will only be deleted from 
#'   the specified arm.
#' @param error_handling An option for how to handle errors returned by the API.
#'   see \code{\link{redcapError}}
#' @param config \code{list} Additional configuration parameters to pass to 
#'   \code{\link[httr]{POST}}. These are appended to any parameters in 
#'   \code{rcon$config}.
#' @param api_param \code{list} Additional API parameters to pass into the
#'   body of the API call. This provides users to execute calls with options
#'   that may not otherwise be supported by \code{redcapAPI}.
#' 
#' @section REDCap API Documentation:
#' This method allows you to delete Arms from a project. 
#' Notice: Because of this method's destructive nature, it is only 
#' available for use for projects in Development status. Additionally, 
#' please be aware that deleting an arm also automatically deletes all 
#' events that belong to that arm, and will also automatically delete 
#' any records/data that have been collected under that arm (this is 
#' non-reversible data loss).
#' 
#' NOTE: This only works for longitudinal projects.
#' 
#' @section REDCap Version:
#' At least 8.1.17+ (and likely some earlier versions)
#' 
#' @return 
#' None.
#' 
#' @references
#' Please refer to your institution's API documentation.
#' 
#' @export

deleteArms <- function(rcon, 
                       arms, 
                       error_handling = getOption("redcap_error_handling", "error"), 
                       config = list(), 
                       api_param = list()){
  
  coll <- checkmate::makeAssertCollection()
  
  checkmate::assert_class(x = rcon,
                          classes = "redcapApiConnection",
                          add = coll)
  
  checkmate::assert_integerish(x = arms, 
                               add = coll)
  
  error_handling <- checkmate::matchArg(x = error_handling, 
                                        choices = c("null", "error"),
                                        add = coll)
  
  checkmate::assert_list(x = config,
                         names = "named",
                         add = coll)
  
  checkmate::assert_list(x = api_param, 
                         names = "named",
                         add = coll)
  
  checkmate::reportAssertions(coll)
  
  body <- list(content = "arm",
               action = "delete")
  
  body <- c(body, 
            vectorToApiBodyList(arms, "arms"))
  
  response <- makeApiCall(rcon, 
                          body = c(body, api_param), 
                          config = config)
  
  redcapError(response, error_handling = error_handling)
  
  if (response$status_code == 200){
    as.numeric(as.character(response))
  }
}

# Aliases -----------------------------------------------------------

#' @rdname deleteArms
#' @export

delete_arms <- deleteArms
