#' @name deleteFiles
#' @title Delete A File 
#' 
#' @description This method allows you to remove a document that has been 
#' attached to an individual record for a File Upload field. Please note 
#' that this method may also be used for Signature fields (i.e. File Upload 
#' fields with 'signature' validation type).
#' 
#' @param rcon A REDCap connection object as generated by 
#'   \code{redcapConnection}.
#' @param record \code{numeric(1)} or \code{character(1)}. The record ID 
#'   with the file to be deleted.
#' @param field \code{character(1)} the name of the field that contains the file.
#' @param event \code{character} with maximum length of one.  The unique event 
#'   name - only for longitudinal projects
#' @param repeat_instance \code{numeric(1)} with maximum length of one. Only for 
#'   projects with repeating instruments/events. The repeat instance number 
#'   of the repeating event (if longitudinal) or the repeating instrument 
#'   (if classic or longitudinal). Default value is '1'.
#' @param error_handling An option for how to handle errors returned by the API.
#'   see \code{\link{redcapError}}
#' @param config \code{list} Additional configuration parameters to pass to 
#'   \code{\link[httr]{POST}}. These are appended to any parameters in 
#'   \code{rcon$config}.
#' @param api_param \code{list} Additional API parameters to pass into the
#'   body of the API call. This provides users to execute calls with options
#'   that may not otherwise be supported by \code{redcapAPI}.
#'   
#' @section REDCap API Documentation:
#' This method allows you to remove a document that has been attached to an 
#' individual record for a File Upload field. Please note that this method 
#' may also be used for Signature fields (i.e. File Upload fields with 
#' 'signature' validation type).
#' 
#' @section REDCap Version:
#' At least 8.1.17+ (and likely some earlier versions)
#' 
#' @return 
#' The number of deleted records.
#' 
#' @references
#' Please refer to your institution's API documentation.
#' 
#' @export

deleteFiles <- function(rcon, 
                        record, 
                        field, 
                        event = character(0), 
                        repeat_instance = 1,
                        error_handling = getOption("redcap_error_handling", "error"), 
                        config = list(), 
                        api_param = list()){
  
  coll <- checkmate::makeAssertCollection()
  
  checkmate::assert_class(x = rcon,
                          classes = "redcapApiConnection",
                          add = coll)
  
  if (!checkmate::test_integerish(x = record) && 
      !checkmate::test_character(x = record)){
    coll$push(sprintf("`record` must be either `integerish` or `character`, but is a %s", 
                      class(record)))
  }
  
  checkmate::assert_character(x = field, 
                              len = 1, 
                              add = coll)
  
  checkmate::assert_character(x = event, 
                              max.len = 1, 
                              add = coll)
  
  checkmate::assert_integerish(x = repeat_instance, 
                               len = 1, 
                               add = coll)
  
  error_handling <- checkmate::matchArg(x = error_handling, 
                                        choices = c("null", "error"),
                                        add = coll)
  
  checkmate::assert_list(x = config,
                         names = "named",
                         add = coll)
  
  checkmate::assert_list(x = api_param, 
                         names = "named",
                         add = coll)
  
  checkmate::reportAssertions(coll)
  
  body <- list(content = "file", 
               action = "delete", 
               record = record, 
               field = field, 
               repeat_instance = repeat_instance, 
               returnFormat = "csv")
  
  if (length(event) > 0){
    body <- c(body, 
              list(event = event))
  }
  
  response <- makeApiCall(rcon, 
                          body = c(body, api_param), 
                          config = config)
  
  redcapError(response, error_handling = error_handling)
  
  if (response$status_code == 200){
    message("File deletion successful: \n",
            sprintf("  Record ID: %s\n", record), 
            sprintf("  Field name: %s\n", field), 
            sprintf("  Event name: %s\n", event), 
            sprintf("  Repeat instance: %s", repeat_instance))
  }
}

# Aliases -----------------------------------------------------------

#' @rdname deleteFiles
#' @export

delete_files <- deleteFiles
