#' @name exportProjectInfo
#' @title Export Project Information
#' 
#' @description Retrieve Information about a REDCap database project.
#' 
#' @param rcon A REDCap connection object as generated by \code{redcapConnection}.
#' @param error_handling An option for how to handle errors returned by the API.
#'   see \code{\link{redcapError}}
#' @param config \code{list} Additional configuration parameters to pass to 
#'   \code{\link[httr]{POST}}. These are appended to any parameters in 
#'   \code{rcon$config}.
#' @param api_param \code{list} Additional API parameters to pass into the
#'   body of the API call. This provides users to execute calls with options
#'   that may not otherwise be supported by \code{redcapAPI}.
#'   
#' @section REDCap API Documentation:
#' This method allows you to export some of the basic attributes of a given 
#' REDCap project, such as the project's title, if it is longitudinal, if 
#' surveys are enabled, the time the project was created and moved to 
#' production, etc.
#' 
#' @section REDCap Version:
#' 5.8.2+ 
#' 
#' @section Known REDCap Limitations:
#' None.
#'
#' @return 
#' Returns a data frame with one row and the following columns:
#' 
#' \itemize{
#'  \item{\code{project_id}  \code{character}}
#'  \item{\code{project_title} \code{character}}
#'  \item{\code{creation_time} \code{POSIXct}}
#'  \item{\code{production_time} \code{POSIXct}}
#'  \item{\code{in_production} \code{logical}}
#'  \item{\code{project_language} \code{character}}
#'  \item{\code{purpose} \code{character}}
#'  \item{\code{purpose_other} \code{character}}
#'  \item{\code{project_notes} \code{character}}
#'  \item{\code{custom_record_label} \code{character}}
#'  \item{\code{secondary_unique_field} \code{character}}
#'  \item{\code{is_longitudinal} \code{logical}}
#'  \item{\code{surveys_enabled} \code{logical}}
#'  \item{\code{scheduling_enabled} \code{logical}}
#'  \item{\code{record_autonumbering_enabled} \code{logical}}
#'  \item{\code{randomization_enabled} \code{logical}}
#'  \item{\code{ddp_enabled} \code{logical}}
#'  \item{\code{project_irb_number} \code{character}}
#'  \item{\code{project_grant_number} \code{character}}
#'  \item{\code{project_pi_firstname} \code{character}}
#'  \item{\code{project_pi_lastname} \code{character}}
#'  \item{\code{display_today_now_button} \code{logical}}
#'  \item{\code{has_repeating_instruments_or_events} \code{logical}}
#' }
#'
#' @author Benjamin Nutter
#'
#' @references
#' Please refer to your institution's API documentation.
#' 
#' @export

exportProjectInfo <- function(rcon, 
                              error_handling = getOption("redcap_error_handling", "error"), 
                              config = list(), 
                              api_param = list()){
  coll <- checkmate::makeAssertCollection()
  
  checkmate::assert_class(x = rcon,
                          classes = "redcapApiConnection",
                          add = coll)
  
  error_handling <- checkmate::matchArg(x = error_handling, 
                                        choices = c("null", "error"),
                                        add = coll)
  
  checkmate::assert_list(x = config,
                         names = "named",
                         add = coll)
  
  checkmate::assert_list(x = api_param, 
                         names = "named",
                         add = coll)
  
  checkmate::reportAssertions(coll)
  
  body <- list(content = "project", 
               format = "csv", 
               returnFormat = "csv")
  
  response <- makeApiCall(rcon, 
                          body = c(body, api_param), 
                          config = config)
  
  redcapError(response, error_handling = error_handling)
  
  ProjectInfo <- utils::read.csv(text = as.character(response),
                                 stringsAsFactors = FALSE,
                                 na.strings = "")
  
  to_posixct <- c("creation_time", 
                  "production_time")
  
  to_logical <- c("in_production", 
                  "is_longitudinal", 
                  "surveys_enabled", 
                  "scheduling_enabled", 
                  "record_autonumbering_enabled", 
                  "randomization_enabled", 
                  "ddp_enabled", 
                  "display_today_now_button", 
                  "has_repeating_instruments_or_events")
  
  ProjectInfo[to_posixct] <- 
    lapply(ProjectInfo[to_posixct], 
           as.POSIXct)
  
  ProjectInfo[to_logical] <- 
    lapply(ProjectInfo[to_logical], 
           as.logical)
  
  ProjectInfo
}

# ALIASES -----------------------------------------------------------

#' @rdname exportProjectInfo
#' @export

export_project_info <- exportProjectInfo
