#' @name exportEvents
#' @aliases exportEvents.redcapApiConnection
#' @aliases exportEvents.redcapDbConnection
#' @export exportEvents
#' @importFrom httr POST
#'
#' @title Export the Events for a Project
#' @description Retrieve a data frame giving the users, expiration dates,
#' and data access privileges for each user.
#'
#' @param rcon A REDCap connection object as generated by \code{redcapConnection}.
#' @param arms A numeric vector or arm numbers to retrieve. In REDCap 6.5.0, 
#'   using this argument results in an empty data frame being returned.
#' @param ... Arguments to be passed to other methods.
#' 
#' @section REDCap Version:
#' 6.5.0+ (perhaps earlier, need to confirm its introduction)
#'
#' @details
#' From the REDCap API Documentation:
#'
#' This function allows you to export the Arms for a project
#' 
#' NOTE: this only works for longitudinal projects. 
#' 
#' It is not sufficient to make the project a longitudinal project. The
#' project must satisfy one of two conditions: 1) have at least two arms and
#' one event defined; or 2) have one arm and at least two events defined. If 
#' neither of these conditions are satisfied, the API will return a message
#' such as \code{ERROR: You cannot export arms for classic projects}, an 
#' error message that isn't as descriptive of the nature of the problem as 
#' we might like.
#'
#' @author Benjamin Nutter
#'
#' @references
#' Please refer to your institution's API documentation.
#'
#' Additional details on API parameters are found on the package wiki at
#' \url{https://github.com/nutterb/redcapAPI/wiki/REDCap-API-Parameters}
#'
#' @examples
#' \dontrun{
#' #*** Note: I cannot provide working examples without
#' #*** compromising security.  Instead, I will try to
#' #*** offer up sample code with the matching results
#' }
#'

exportEvents <- function(rcon, ...) UseMethod("exportEvents")

#' @rdname exportEvents
#' @export

exportEvents.redcapDbConnection <- function(rcon, arms = NULL, ...){
  message("Please accept my apologies.  The exportArms method for redcapDbConnection objects\n",
          "has not yet been written.  Please consider using the API.")
}

#' @rdname exportUsers
#' @export

exportEvents.redcapApiConnection <- 
  function(rcon, arms = NULL, ...,
           error_handling = getOption("redcap_error_handling"))
{
  checkmate::assertChoice(error_handling, c("null", "error"))  
  
  #* parameters for the Users File Export
  body <- list(token=rcon$token, 
               content='event', 
               format='csv', 
               returnFormat='csv')
  
  if (!is.null(arms)) body[['arms']] <- paste0(arms, collapse = ",")
  
  #* Export Users file and convert to data frame
  x <- httr::POST(url=rcon$url, 
                  body=body, 
                  config=rcon$config)
  
  if (x$status_code != 200) return(redcap_error(x, error_handling))
  
  read.csv(textConnection(as.character(x)),
           stringsAsFactors = FALSE,
           na.strings = "")
  }
