#' @name exportSurveyParticipants
#' @title Export Survey Participants
#' 
#' @description Export a Survey Participant List
#' 
#' @param rcon A REDCap connection object as generated by \code{redcapConnection}.
#' @param instrument \code{character(1)} the unique instrument name as seen 
#'   in the second column of the Data Dictionary. This instrument must be 
#'   enabled as a survey in the project. 
#' @param event \code{character}  with maximum length of 1. The unique event 
#'   name (for longitudinal projects only).
#' @param error_handling An option for how to handle errors returned by the API.
#'   see \code{\link{redcapError}}
#' @param config \code{list} Additional configuration parameters to pass to 
#'   \code{\link[httr]{POST}}. These are appended to any parameters in 
#'   \code{rcon$config}.
#' @param api_param \code{list} Additional API parameters to pass into the
#'   body of the API call. This provides users to execute calls with options
#'   that may not otherwise be supported by \code{redcapAPI}.
#'   
#' @section REDCap Version:
#' 5.8.2+ 
#' 
#' @section Known REDCap Limitations:
#' None.
#'
#' @return 
#' Returns a data frame
#' 
#' \itemize{
#'   \item{\code{email} Participant e-mail address} 
#'   \item{\code{email_occurrence} represents the current count that the email 
#'     address has appeared in the list (because emails can be used more 
#'     than once), thus email + email_occurrence represent a unique value pair.}
#'   \item{\code{identifier} } 
#'   \item{\code{record} }
#'   \item{\code{invitation_sent_status} Indicates if an invitation has been sent.} 
#'   \item{\code{invitation_send_time} is the date/time in which the next 
#'     invitation will be sent, and is blank if there is no invitation that 
#'     is scheduled to be sent} 
#'   \item{\code{response_status} represents whether the participant has responded to the survey}
#'   \item{\code{survey_access_code}} 
#'   \item{\code{survey_link}} 
#'   \item{\code{survey_queue_link}}
#' }
#'
#' @author Benjamin Nutter
#'
#' @references
#' Please refer to your institution's API documentation.
#' 
#' @export

exportSurveyParticipants <- function(rcon, 
                                     instrument, 
                                     event = character(0),
                                     error_handling = getOption("redcap_error_handling", "error"), 
                                     config = list(), 
                                     api_param = list()){
  
  coll <- checkmate::makeAssertCollection()
  
  checkmate::assert_class(x = rcon,
                          classes = "redcapApiConnection",
                          add = coll)
  
  checkmate::assert_character(x = instrument, 
                              len = 1, 
                              add = coll)
  
  checkmate::assert_character(x = event, 
                              max.len = 1, 
                              add = coll)
  
  error_handling <- checkmate::matchArg(x = error_handling, 
                                        choices = c("null", "error"),
                                        add = coll)
  
  checkmate::assert_list(x = config,
                         names = "named",
                         add = coll)
  
  checkmate::assert_list(x = api_param, 
                         names = "named",
                         add = coll)
  
  checkmate::reportAssertions(coll)
  
  body <- list(content = "participantList", 
               instrument = instrument, 
               format = "csv", 
               returnFormat = "csv")
  
  if (length(event)){
    body <- c(body, 
              list(event = event))
  }
  
  response <- makeApiCall(rcon, 
                          body = c(body, api_param), 
                          config = config)
  
  redcapError(response, error_handling = error_handling)
  
  Participant <- 
    utils::read.csv(text = as.character(response),
                    stringsAsFactors = FALSE,
                    na.strings = "")
  
  Participant$invitation_sent_status <- 
    as.logical(Participant$invitation_sent_status)
  
  Participant$invitation_send_time <- 
    as.POSIXct(Participant$invitation_send_time)
  
  Participant$response_status <- 
    c("No Response", "Partial", "Completed")[Participant$response_status + 1]
  
  Participant
}

# Aliases -----------------------------------------------------------

export_survey_participants <- exportSurveyParticipants