#' @name exportProjectXml
#' @title Export Project XML Data
#' 
#' @description Export Entire Project as REDCap XML File (containing metadata & data)
#' 
#' @param rcon A REDCap connection object as generated by \code{redcapConnection}.
#' @param filepath \code{character(1)} path to the location where the XML file will be written.
#' @param return_metadata_only \code{logical(1)} When \code{TRUE},
#'   returns only metadata (all fields, forms, events, and arms), 
#'   whereas \code{FALSE} returns all metadata and also data (and optionally 
#'   filters the data according to any of the optional parameters provided 
#'   in the request)
#' @param records \code{character} or \code{numeric} vector of record names 
#'   specifying specific records you wish to pull (by default, all 
#'   records are pulled)
#' @param fields \code{character} vector of field names 
#'   specifying specific fields you wish to pull (by default, 
#'   all fields are pulled)
#' @param events \code{character} vector of unique event names that you wish 
#'   to pull records for - only for longitudinal projects
#' @param export_survey_fields \code{logical(1)} specifies whether or not to 
#'   export the survey identifier field (e.g., 'redcap_survey_identifier') or 
#'   survey timestamp fields (e.g., instrument+'_timestamp') when surveys are 
#'   utilized in the project. If you do not pass in this flag, it will default 
#'   to \code{FALSE}. If set to \code{TRUE}, it will return the redcap_survey_identifier 
#'   field and also the survey timestamp field for a particular survey when at 
#'   least one field from that survey is being exported. NOTE: If the survey 
#'   identifier field or survey timestamp fields are imported via API data 
#'   import, they will simply be ignored since they are not real fields in
#'    the project but rather are pseudo-fields.
#' @param export_data_access_groups \code{logical(1)} specifies whether or not 
#'   to export the 'redcap_data_access_group' field when data access groups 
#'   are utilized in the project. If you do not pass in this flag, it will 
#'   default to \code{FALSE}. NOTE: This flag is only viable if the user 
#'   whose token is being used to make the API request is not in a data access 
#'   group. If the user is in a group, then this flag will revert to its
#'  default value.
#' @param filter_logic \code{character} of logic text with (maximum length of 1) 
#'   (e.g., \code{"[age] > 30"}) for filtering the data to be returned by 
#'   this API method, in which the API will only return the records 
#'   (or record-events, if a longitudinal project) where the logic evaluates as 
#'   TRUE. This parameter is blank/null by default unless a value is supplied. 
#'   Please note that if the filter logic contains any incorrect syntax, 
#'   the API will respond with an error message.
#' @param export_files \code{logical(1)} \code{TRUE} will cause the XML 
#'   returned to include all files uploaded for File Upload and Signature 
#'   fields for all records in the project, whereas FALSE will cause all 
#'   such fields not to be included. NOTE: Setting this option to TRUE can 
#'   make the export very large and may prevent it from completing if the 
#'   project contains many files or very large files.
#' @param meta_data \code{data.frame}, the data dictionary as returned by 
#'   \code{exportMetaData}. If \code{NULL}, the data dictionary will be 
#'   downloaded from the API.
#' @param event_list \code{data.frame}, the event list as returned by 
#'   \code{exportEvents}.
#' @param error_handling An option for how to handle errors returned by the API.
#'   see \code{\link{redcapError}}
#' @param config \code{list} Additional configuration parameters to pass to 
#'   \code{\link[httr]{POST}}. These are appended to any parameters in 
#'   \code{rcon$config}.
#' @param api_param \code{list} Additional API parameters to pass into the
#'   body of the API call. This provides users to execute calls with options
#'   that may not otherwise be supported by \code{redcapAPI}.
#'   
#' @section REDCap API Documentation:
#' This method allows you to export a list of the data collection instruments 
#' for a project. This includes their unique instrument name as seen in the 
#' second column of the Data Dictionary, as well as each instrument's 
#' corresponding instrument label, which is seen on a project's left-hand 
#' menu when entering data. The instruments will be ordered according to their 
#' order in the project.
#' 
#' @section REDCap Version:
#' 5.8.2+ 
#' 
#' @section Known REDCap Limitations:
#' None.
#' 
#' @author Benjamin Nutter
#' 
#' @export

exportProjectXml <- function(rcon, 
                             filepath, 
                             return_metadata_only = FALSE, 
                             records = character(0), 
                             fields = character(0), 
                             events = character(0), 
                             export_survey_fields = FALSE, 
                             export_data_access_groups = FALSE, 
                             filter_logic = character(0), 
                             export_files = FALSE, 
                             meta_data = NULL, 
                             event_list = NULL,
                             error_handling = getOption("redcap_error_handling", "error"), 
                             config = list(), 
                             api_param = list()){
  coll <- checkmate::makeAssertCollection()

  checkmate::assert_class(x = rcon,
                          classes = "redcapApiConnection",
                          add = coll)
  
  checkmate::assert_character(x = filepath,
                              len = 1, 
                              add = coll)
  
  checkmate::assert_logical(x = return_metadata_only, 
                            len = 1, 
                            add = coll)
  
  checkmate::assert_character(x = records, 
                              add = coll)
  
  checkmate::assert_character(x = fields, 
                              add = coll)
  
  checkmate::assert_character(x = events, 
                              add = coll)
  
  checkmate::assert_logical(x = export_survey_fields, 
                            len = 1, 
                            add = coll)
  
  checkmate::assert_logical(x = export_data_access_groups, 
                            len = 1, 
                            add = coll)
  
  checkmate::assert_character(x = filter_logic, 
                              add = coll)
  
  checkmate::assert_logical(x = export_files, 
                            len = 1, 
                            add = coll)
  
  checkmate::assert_data_frame(x = meta_data, 
                               null.ok = TRUE, 
                               add = coll)
  
  checkmate::assert_data_frame(x = event_list, 
                               null.ok = TRUE, 
                               add = coll)
  
  error_handling <- checkmate::matchArg(x = error_handling, 
                                        choices = c("null", "error"),
                                        add = coll)
  
  checkmate::assert_list(x = config,
                         names = "named",
                         add = coll)
  
  checkmate::assert_list(x = api_param, 
                         names = "named",
                         add = coll)
    
  checkmate::reportAssertions(coll)
  
  # Argument Validation - Round Two ---------------------------------
  
  MetaData <- .exportRecords_getMetaData(meta_data, rcon)
  
  .exportRecords_validateFieldNames(fields = fields, 
                                    MetaData = MetaData, 
                                    coll = coll)
  
  .exportRecords_validateEventNames(bundle = event_list, 
                                    rcon = rcon,
                                    events = events, 
                                    MetaData = MetaData, 
                                    coll = coll)
  
  checkmate::reportAssertions(coll)
  
  # Functional Code -------------------------------------------------
  
  body <- 
    c(list(content = "project_xml", 
           token = rcon$token, 
           returnMetaDataOnly = as.character(return_metadata_only), 
           exportSurveyFields = as.character(export_survey_fields), 
           exportDataAccessGroups = as.character(export_data_access_groups), 
           filterLogic = filter_logic, 
           exportFiles = as.character(export_files)),
      vectorToApiBodyList(records, "records"), 
      vectorToApiBodyList(fields, "fields"), 
      vectorToApiBodyList(events, "events")
    )
  
  response <- makeApiCall(rcon, 
                          body = c(body, api_param), 
                          config = config)
  
  redcapError(response, error_handling = error_handling)
  
  xml_code <- rawToChar(response$content)
  
  writeLines(text = xml_code, 
             con = filepath)
}

# Aliases -----------------------------------------------------------

#' @rdname exportProjectXml
#' @export

exportProjectXML <- exportProjectXml

#' @rdname exportProjectXml
#' @export

export_project_xml <- exportProjectXml

#' @rdname exportProjectXml
#' @export

export_project_XML <- exportProjectXml
