#' @name exportSurveyQueueLink
#' @title Export a Survey Queue Link for a Participant
#' 
#' @description This method returns a unique Survey Queue link (i.e., a URL) 
#'   in plain text format for the specified record in a project that is
#'  utilizing the Survey Queue feature. If the user does not have 
#'  'Survey Distribution Tools' privileges, they will not be able to use 
#'  this method, and an error will be returned. If the Survey Queue feature 
#'  has not been enabled in the project, an error will be returned.
#'   
#' @param rcon A REDCap connection object as generated by \code{redcapConnection}.
#' @param record \code{character(1)} or \code{numeric(1)}, the record ID for 
#'   which the survey link will be downloaded. 
#' @param error_handling An option for how to handle errors returned by the API.
#'   see \code{\link{redcapError}}
#' @param config \code{list} Additional configuration parameters to pass to 
#'   \code{\link[httr]{POST}}. These are appended to any parameters in 
#'   \code{rcon$config}.
#' @param api_param \code{list} Additional API parameters to pass into the
#'   body of the API call. This provides users to execute calls with options
#'   that may not otherwise be supported by \code{redcapAPI}.
#'   
#' @section REDCap API Documentation:
#' This method returns a unique Survey Queue link (i.e., a URL) 
#'   in plain text format for the specified record in a project that is
#'  utilizing the Survey Queue feature. If the user does not have 
#'  'Survey Distribution Tools' privileges, they will not be able to use 
#'  this method, and an error will be returned. If the Survey Queue feature 
#'  has not been enabled in the project, an error will be returned.
#' 
#' @section REDCap Version:
#' 5.8.2+ 
#' 
#' @section Known REDCap Limitations:
#' None.
#'
#' @author Benjamin Nutter
#'
#' @references
#' Please refer to your institution's API documentation.
#' 
#' @export

exportSurveyQueueLink <- function(rcon, 
                                   record, 
                                   error_handling = getOption("redcap_error_handling", "error"), 
                                   config = list(), 
                                   api_param = list()){
  coll <- checkmate::makeAssertCollection()
  
  checkmate::assert_class(x = rcon,
                          classes = "redcapApiConnection",
                          add = coll)
  
  if (!checkmate::test_integerish(x = record, len = 1) &&
      !checkmate::test_character(x = record, len = 1)){
    coll$push("`record` must be either a `character(1)` or `integerish(1)`")
  }
  
  error_handling <- checkmate::matchArg(x = error_handling, 
                                        choices = c("null", "error"),
                                        add = coll)
  
  checkmate::assert_list(x = config,
                         names = "named",
                         add = coll)
  
  checkmate::assert_list(x = api_param, 
                         names = "named",
                         add = coll)
  
  checkmate::reportAssertions(coll)
  
  body <-
      list(content = "surveyQueueLink", 
           returnFormat = "csv",
           record = record)
  
  response <- makeApiCall(rcon, 
                          body = c(body, api_param), 
                          config = config)
  
  redcapError(response, error_handling = error_handling)
  
  rawToChar(response$content)
}

# Aliases -----------------------------------------------------------

export_survey_queue_link <- exportSurveyQueueLink