#' @name exportReports
#' @title Export Reports
#' 
#' @description This method allows you to export the data set of a report created on a project's 'Data Exports, Reports, and Stats' page.
#' 
#' @param rcon A REDCap connection object as generated by \code{redcapConnection}.
#' @param report_id \code{character(1)} or \code{numeric(1)} giving the report 
#'   ID to download.
#' @param factors \code{logical(1)}.  Determines if categorical data from the 
#'   database is 
#'   returned as numeric codes or labelled factors. See 'Checkbox Variables'
#'   for more on how this interacts with the \code{checkboxLabels} argument.
#' @param labels \code{logical(1)}.  Determines if the variable labels are applied to 
#'   the data frame.
#' @param dates \code{logical(1)} Determines if date variables are converted to POSIXct 
#'   format during the download.
#' @param checkboxLabels Logical. Determines the format of labels in checkbox 
#'   variables.  If \code{FALSE} labels are applies as "Unchecked"/"Checked".  
#'   If \code{TRUE}, they are applied as ""/"[field_labe]" where [field_label] 
#'   is the label assigned to the level in the data dictionary. This option 
#'   is only available after REDCap version 6.0.
#' @param bundle A \code{redcapBundle} object as created by \code{exportBundle}.
#' @param error_handling An option for how to handle errors returned by the API.
#'   see \code{\link{redcapError}}
#' @param config \code{list} Additional configuration parameters to pass to 
#'   \code{\link[httr]{POST}}. These are appended to any parameters in 
#'   \code{rcon$config}.
#' @param api_param \code{list} Additional API parameters to pass into the
#'   body of the API call. This provides users to execute calls with options
#'   that may not otherwise be supported by \code{redcapAPI}.
#' 
#' @details
#' A record of exports through the API is recorded in the Logging section of 
#' the project.
#' 
#' Reports are exported based on their id number, which can be looked up in 
#' the Reports page of a project
#' 
#' @section REDCap API Documentation (6.5.0):
#' This function allows you to export the data set of a report created on a project's 
#' "Data Exports, Reports, and Stats" page.
#' 
#' Note about export rights (6.0.0+): Please be aware that Data Export user rights will be 
#' applied to this API request. For example, if you have "No Access" data export rights 
#' in the project, then the API report export will fail and return an error. And if you 
#' have "De-Identified" or "Remove all tagged Identifier fields" data export rights, 
#' then some data fields *might* be removed and filtered out of the data set returned 
#' from the API. To make sure that no data is unnecessarily filtered out of your API 
#' request, you should have "Full Data Set" export rights in the project.
#' 
#' @section REDCap Version:
#' 6.0.0+
#' 
#' @section Known REDCap Limitations:
#' None
#' 
#' @author Benjamin Nutter
#' 
#' @export

exportReports <- function(rcon, 
                          report_id,
                          factors = TRUE, 
                          labels = TRUE, 
                          dates = TRUE, 
                          checkboxLabels = FALSE,
                          bundle = getOption("redcap_bundle"), 
                          error_handling = getOption("redcap_error_handling", "error"), 
                          config = list(), 
                          api_param = list()){
  # Argument Validation ---------------------------------------------
  
  coll <- checkmate::makeAssertCollection()
  
  checkmate::assert_class(x = rcon, 
                          classes = "redcapApiConnection", 
                          add = coll)

  if (!checkmate::test_character(x = report_id) &&
      !checkmate::test_integerish(x = report_id)){
    coll$push("`report_id` must be either a character or integerish vector.")
  }  
    
  checkmate::assert_logical(x = factors, 
                            len = 1, 
                            add = coll)

  checkmate::assert_logical(x = labels, 
                            len = 1, 
                            add = coll)
  
  checkmate::assert_logical(x = dates, 
                            len = 1, 
                            add = coll)
  
  checkmate::assert_logical(x = checkboxLabels, 
                            len = 1, 
                            add = coll)
  
  error_handling <- checkmate::matchArg(x = error_handling, 
                                        choices = c("null", "error"),
                                        add = coll)
  
  checkmate::assert_list(x = config,
                         names = "named",
                         add = coll)
  
  checkmate::assert_list(x = api_param, 
                         names = "named",
                         add = coll)
  
  checkmate::reportAssertions(coll)
  
  MetaData <- .exportRecords_getMetaData(bundle, rcon)
  
  version <- .exportRecords_getVersion(bundle = bundle, 
                                       rcon = rcon)
  
  # Get the Data from the API ---------------------------------------
  
  body <- list(content = "report", 
               report_id = report_id, 
               format = "csv", 
               returnFormat = "csv")
  
  response <- makeApiCall(rcon, 
                          body = c(body, api_param), 
                          config = config)
  
  redcapError(response, error_handling = error_handling)
  
  RedcapData <- utils::read.csv(text = as.character(response),
                                stringsAsFactors = FALSE,
                                na.strings = "")
  
  # Format data according to arguments ------------------------------
  
  #* synchronize underscore codings between records and meta data
  #* Only affects calls in REDCap versions earlier than 5.5.21
  if (utils::compareVersion(version, "6.0.0") == -1){
    MetaData <- syncUnderscoreCodings(records = RedcapData, 
                                      meta_data = MetaData)
  }
  
  RedcapData <- fieldToVar(records = RedcapData,
                           meta_data = MetaData,
                           factors = factors,
                           dates = dates,
                           checkboxLabels = checkboxLabels)
  
  RedcapData <- .exportRecords_addLabelToData(RedcapData = RedcapData, 
                                              MetaData = MetaData, 
                                              field_names = names(RedcapData), 
                                              labels = labels, 
                                              version = version)
  
  RedcapData
}

# Aliases -----------------------------------------------------------

export_reports <- exportReports