#' @name exportUsers
#' @aliases exportUsers.redcapApiConnection
#' @aliases exportUsers.redcapDbConnection
#' @export exportUsers
#' @importFrom httr POST
#'
#' @title Export the Users for a Project
#' @description Retrieve a data frame giving the users, expiration dates,
#' and data access privileges for each user.
#'
#' @param rcon A REDCap connection object as generated by \code{redcapConnection}.
#' @param date Logical. Indicates if the expiration date is converted to a
#'   \code{POSIXct} object.
#' @param label Logical. Indicates if the data export and form access rights are
#'   converted to factor objects.
#' @param ... Arguments to be passed to other methods.
#'
#' @details
#' For some reason I have yet to identify, some User Tables do not
#' export correctly. In some situations, the fields are all shifted one
#' column to the left and the form names are not always exported.
#' This seems to be more common in projects still in Development mode.
#' I have seen one instance of a project in Production where one user had
#' one more column given than any other user.  If you notice this behavior,
#' please report it to me as it may help me narrow down the source of the problem
#' 
#' @section REDCap API Documentation (6.5.0):
#' This function allows you to export the users for a project
#' 
#' @section REDCap Version:
#' 5.8.2 (Perhaps earlier) 
#' 
#' @section Known REDCap Limitations:
#' None
#' 
#' @return 
#' Returns a data frame. The number of columns in the data frame will depend on your 
#' version of REDCap.
#' \itemize{
#'   \item{\code{username }}{User name}
#'   \item{\code{email }}{The user's e-mail address}
#'   \item{\code{firstname }}{The user's first name}
#'   \item{\code{lastname }}{The user's last name}
#'   \item{\code{expiration }}{The expiration date of the user's access to the project}
#'   \item{\code{data_access_group }}{The data access group the user is assigned to}
#'   \item{\code{data_export }}{The user's data export rights. 0=no access, 
#'     2=De-Identified, 1=Full Data Set}
#'   \item{\code{mobile_app }}{(6.5.0+) Flag for if the user has permissions for the 
#'     mobile application}
#'   \item{\code{mobile_app_download_data }}{(6.5.0+) Flag for if the user may download
#'     data from the mobile app}
#' }
#' 
#' The data frame will have one additional column for each form giving the user's 
#' form-level permissions in the project.  0=no access, 2=read only, 
#' 1=view records/responses and
#' edit records (survey responses are read-only), 3 = edit survey responses
#'
#' @author Benjamin Nutter
#'
#' @references
#' Please refer to your institution's API documentation.
#'
#' Additional details on API parameters are found on the package wiki at
#' \url{https://github.com/nutterb/redcapAPI/wiki/REDCap-API-Parameters}
#'

exportUsers <- function(rcon, ...) UseMethod("exportUsers")

#' @rdname exportUsers
#' @export

exportUsers.redcapDbConnection <- function(rcon, date=TRUE, label=TRUE, ...){
  message("Please accept my apologies.  The exportUsers method for redcapDbConnection objects\n",
          "has not yet been written.  Please consider using the API.")
}

#' @rdname exportUsers
#' @export

exportUsers.redcapApiConnection <- function(rcon, date=TRUE, label=TRUE, ...,
                                            meta_data = NULL){
  #* parameters for the Users File Export
  body <- list(token = rcon$token, 
               content = 'user', 
               format = 'csv', 
               returnFormat = 'csv')
  
  #* Export Users file and convert to data frame
  x <- httr::POST(url = rcon$url, 
                  body = body, 
                  config = rcon$config)
  
  if (x$status_code != "200") 
    stop(paste0(x$status_code, ": ", as.character(x)))
  
  x <- utils::read.csv(textConnection(as.character(x)),
                       stringsAsFactors = FALSE,
                       na.strings = "")
                             
  #* convert expiration date to POSIXct class
  if (date) x$expiration <- as.POSIXct(x$expiration, format="%Y-%m-%d")
  
  #* convert data export and form editing privileges to factors
  if (label){
    x$data_export <- 
      factor(x$data_export, 
             levels = c(0, 2, 1), 
             labels = c("No access", "De-identified", "Full data set"))
    
    if (is.null(meta_data)) meta_data <- exportMetaData(rcon)
    form_names <- unique(meta_data$form)

    x[, form_names] <-
      lapply(x[, form_names, drop = FALSE],
             FUN = factor, 
             levels = c(0, 2, 1, 3),
             labels = c("No access", "Read only", 
                        "view records/responses and edit records", 
                        "Edit survey responses"))
  }
  
  x
}