#' @name exportInstrumentEventMappings
#' @title Export Instrument-Event Mappings
#' 
#' @description This method allows you to export the instrument-event mappings 
#'   for a project (i.e., how the data collection instruments are designated 
#'   for certain events in a longitudinal project).  NOTE: This only works 
#'   for longitudinal projects.
#'   
#' @param rcon A REDCap connection object as generated by \code{redcapConnection}.
#' @param arms Either \code{numeric} or \code{character}. The arm numbers to retrieve.
#' @param error_handling An option for how to handle errors returned by the API.
#'   see \code{\link{redcapError}}
#' @param config \code{list} Additional configuration parameters to pass to 
#'   \code{\link[httr]{POST}}. These are appended to any parameters in 
#'   \code{rcon$config}.
#' @param api_param \code{list} Additional API parameters to pass into the
#'   body of the API call. This provides users to execute calls with options
#'   that may not otherwise be supported by \code{redcapAPI}.
#'
#' @section REDCap API Documentation:
#' This method allows you to export the instrument-event mappings for a 
#' project (i.e., how the data collection instruments are designated 
#' for certain events in a longitudinal project).
#' 
#' NOTE: This only works for longitudinal projects.
#' 
#' @section REDCap Version:
#' 5.8.2+ 
#' 
#' @section Known REDCap Limitations:
#' None.
#'
#' @return 
#' Returns a data frame with two columns
#' 
#' \itemize{
#'   \item{\code{arm_num} }{The Study arm number}
#'   \item{\code{unique_event_name} }{The name of the event}
#'   \item{\code{form}{The name of the form for the arm-event.}}
#' }
#'
#' @author Benjamin Nutter
#'
#' @references
#' Please refer to your institution's API documentation.
#' 
#' @export


exportInstrumentEventMappings <- function(rcon, 
                                          arms = numeric(0), 
                                          error_handling = getOption("redcap_error_handling", "error"), 
                                          config = list(), 
                                          api_param = list()){
  coll <- checkmate::makeAssertCollection()
  
  checkmate::assert_class(x = rcon,
                          classes = "redcapApiConnection",
                          add = coll)
  
  if (!checkmate::test_integerish(x = arms) && 
      !checkmate::test_character(x = arms)){
    coll$push(sprintf("`arms` must be either `integerish` or `character`, but is a %s", 
                      class(arms)))
  }
  
  error_handling <- checkmate::matchArg(x = error_handling, 
                                        choices = c("null", "error"),
                                        add = coll)
  
  checkmate::assert_list(x = config,
                         names = "named",
                         add = coll)
  
  checkmate::assert_list(x = api_param, 
                         names = "named",
                         add = coll)
  
  checkmate::reportAssertions(coll)
  
  body <- list(content = "formEventMapping", 
               format = "csv", 
               returnFormat = "csv")
  
  if (length(arms) > 0){
    body <- c(body, 
              vectorToApiBodyList(arms))
  }
  
  response <- makeApiCall(rcon, 
                          body = c(body, api_param), 
                          config = config)
  
  redcapError(response, error_handling = error_handling)
  
  utils::read.csv(text = as.character(response),
                  stringsAsFactors = FALSE,
                  na.strings = "")
  
}

# ALIASES -----------------------------------------------------------

export_instrument_event_mappings <- exportInstrumentEventMappings