#' @name exportRepeatingInstrumentsAndEvents
#' @title Export Repeating Instruments and Events
#' 
#' @description Export the list of repeated instruments and events from a project.
#' 
#' @param rcon A REDCap connection object as generated by \code{redcapConnection}.
#' @param error_handling An option for how to handle errors returned by the API.
#'   see \code{\link{redcapError}}
#' @param config \code{list} Additional configuration parameters to pass to 
#'   \code{\link[httr]{POST}}. These are appended to any parameters in 
#'   \code{rcon$config}.
#' @param api_param \code{list} Additional API parameters to pass into the
#'   body of the API call. This provides users to execute calls with options
#'   that may not otherwise be supported by \code{redcapAPI}.
#'
#' @section REDCap API Documentation:
#' This method allows you to export a list of the repeated instruments and 
#' repeating events for a project. This includes their unique instrument name 
#' as seen in the second column of the Data Dictionary, as well as each 
#' repeating instrument's corresponding custom repeating instrument label. 
#' For longitudinal projects, the unique event name is also returned for 
#' each repeating instrument. Additionally, repeating events are returned as 
#' separate items, in which the instrument name will be blank/null to 
#' indicate that it is a repeating event (rather than a repeating instrument).
#' 
#' @section REDCap Version:
#' 5.8.2+ 
#' 
#' @section Known REDCap Limitations:
#' None.
#'
#' @author Benjamin Nutter
#'
#' @references
#' Please refer to your institution's API documentation.
#' 
#' @export

exportRepeatingInstrumentsAndEvents <- function(rcon, 
                                                error_handling = getOption("redcap_error_handling", "error"), 
                                                config = list(), 
                                                api_param = list()){
  coll <- checkmate::makeAssertCollection()
  
  checkmate::assert_class(x = rcon,
                          classes = "redcapApiConnection",
                          add = coll)
  
  error_handling <- checkmate::matchArg(x = error_handling, 
                                        choices = c("null", "error"),
                                        add = coll)
  
  checkmate::assert_list(x = config,
                         names = "named",
                         add = coll)
  
  checkmate::assert_list(x = api_param, 
                         names = "named",
                         add = coll)
  
  checkmate::reportAssertions(coll)
  
  body <- list(content = "repeatingFormsEvents", 
               format = "csv")
  
  response <- makeApiCall(rcon, 
                          body = c(body, api_param), 
                          config = config)
  
  redcapError(response, error_handling = error_handling)
  
  utils::read.csv(text = as.character(response),
                  stringsAsFactors = FALSE,
                  na.strings = "")
}

# Aliases -----------------------------------------------------------

#' @rdname exportRepeatingInstrumentsAndEvents
#' @export

export_repeating_instruments_and_events <- exportRepeatingInstrumentsAndEvents