#' @name exportProjectInformation
#' @aliases exportProjectInformation.redcapApiConnection
#' @aliases exportProjectInformation.redcapDbConnection
#' @export exportProjectInformation
#' @importFrom httr POST
#'
#' @title Exports the Project Information
#' @description Retrieve a data frame with the project information.
#'
#' @param rcon A REDCap connection object as generated by \code{redcapConnection}
#' @param ... Arguments to be passed to other methods.
#' 
#' @section REDCap Version:
#' Sometime after 6.0.0 (exact version not yet known)
#'
#' @details If this function is used in a version of REDCap that does not
#'   support the Export Version Number function, the character string
#'   \code{'Version Unknown'} is returned.
#'
#' @author Benjamin Nutter
#'
#' @references
#' Please refer to your institution's API documentation.
#'
#' Additional details on API parameters are found on the package wiki at
#' \url{https://github.com/nutterb/redcapAPI/wiki/REDCap-API-Parameters}
#'


exportProjectInformation <- function(rcon, ...) UseMethod("exportProjectInformation")

#' @rdname exportVersion
#' @export

exportProjectInformation.redcapDbConnection <- function(rcon, ...){
  message("Please accept my apologies.  The exportVersion method for redcapDbConnection objects\n",
          "has not yet been written.  Please consider using the API.")
}

#' @rdname exportVersion
#' @export

exportProjectInformation.redcapApiConnection <- function(rcon, ...){
  body <- list(token = rcon$token, 
               content = 'project',
               format = 'csv',
               returnFormat = 'csv')
  
  x <- httr::POST(url=rcon$url, 
                  body=body,
                  config = rcon$config)
  
  if (x$status_code != 200)
  {
    stop(paste0(x$status_code, ": ", as.character(x)))
  }
  
  read.csv(textConnection(as.character(x)), stringsAsFactors=FALSE, na.strings="")
}