#' @name exportMetaData
#' 
#' @title Export Meta Data from a REDCap Database
#' @description Retrieves the meta data for a REDcap database, including 
#' field names, labels, types, formulas, etc.  This file can be used to parse 
#' levels of factors, apply labels, and other data management tasks once the 
#' data are retrieved
#' 
#' @param rcon A REDCap connection object as generated by \code{redcapConnection.}
#' @param fields A character vector of field names for which the metadata is to 
#'   be retrieved.  
#' @param forms A character vector of forms for which the metadata is to be
#'   retrieved. Note that if a form name is given, all of the fields on that form
#'   will be returned, regardless of whether it is included in \code{fields} or 
#'   not.  Be careful to use the form names in the second column of the data 
#'   dictionary, and not the display names shown on the webpage.
#' @param error_handling An option for how to handle errors returned by the API.
#'   see \code{\link{redcapError}}. One of \code{c("null", "error")}.
#' @param config Additional controls to be passed to other \code{\link[httr]{config}}.
#'   These will be appended to the controls given in \code{rcon}.
#' @param api_param \code{list} Additional API parameters to pass into the
#'   body of the API call. This provides users to execute calls with options
#'   that may not otherwise be supported by \code{redcapAPI}.
#' 
#' @details A record of this export is placed in the REDCap logging page, 
#' but the file that is exported is not stored in the database.
#' 
#' @section REDCap API Documentation:
#' This function allows you to export the metadata for a project
#' 
#' @section REDCap Version:
#' 5.8.2+ (and earlier, but we don't know how much earlier)
#' 
#' @author Jeffrey Horner
#' 
#' @references
#' This functionality was originally developed by Jeffrey Horner in the \code{redcap} package.
#' \url{https://github.com/vubiostat/redcap}
#' 
#' Please refer to your institution's API documentation.
#' 
#' @section Functional Requirements:
#' \enumerate{
#'  \item Return a data frame with the meta data.
#'  \item Throw an error if \code{fields} is not a \code{character}
#'  \item Throw an error if \code{forms} is not a \code{character}
#'  \item Throw an error if \code{error_handling} is not one of \code{c("null", "error")}
#' }
#' 
#' @export

exportMetaData <- function(rcon, 
                           fields = character(0), 
                           forms = character(0), 
                           error_handling = getOption("redcap_error_handling", "null"), 
                           config = list(), 
                           api_param = list()){
  # Argument Validation ---------------------------------------------
  coll <- checkmate::makeAssertCollection()
  
  checkmate::assert_class(x = rcon, 
                          classes = "redcapApiConnection", 
                          add = coll)
  
  checkmate::assert_character(x = fields, 
                              add = coll)
  
  checkmate::assert_character(x = forms,
                              add = coll)
  
  error_handling <- checkmate::matchArg(x = error_handling, 
                                        choices = c("null", "error"))
  
  checkmate::assert_list(x = config, 
                         add = coll)
  
  checkmate::assert_list(x = api_param, 
                         add = coll)
  
  checkmate::reportAssertions(coll)
  
  # Functional Code -------------------------------------------------

  # Build the body object -------------------------------------------
  
  body <- .exportMetaData_makeBodyList(fields = fields, 
                                       forms = forms, 
                                       api_param = api_param)
  
  # Make the API Call -----------------------------------------------

  response <- makeApiCall(rcon = rcon, 
                          body = body, 
                          config = config)
  
  redcapError(response, 
              error_handling = error_handling)
  
  # Return Data Frame -----------------------------------------------
  
  utils::read.csv(text = as.character(response), 
                  stringsAsFactors = FALSE, 
                  na.strings = "")
}

# UNEXPORTED METHODS ------------------------------------------------

.exportMetaData_makeBodyList <- function(fields, forms, api_param){
  body <- list(content = "metadata", 
               format = "csv", 
               returnFormat = "csv")
  
  if (length(fields) > 0){
    fields <- vectorToApiBodyList(fields, "fields")
    body <- c(body, fields)
  }
  
  if (length(forms) > 0){
    forms <- vectorToApiBodyList(forms, "forms")
    body <- c(body, forms)
  }
  
  if (length(api_param) > 0){
    body <- c(body, api_param)
  }
  
  body
}

# ALIASES -----------------------------------------------------------

#' @rdname exportMetaData
#' @export

export_meta_data <- exportMetaData

#' @rdname exportMetaData
#' @export

exportDataDictionary <- exportMetaData

#' @rdname exportMetaData
#' @export

export_data_dictionary <- exportMetaData
