#' @name exportSurveyLink
#' @title Export a Survey Link for a Participant
#' 
#' @description This method returns a unique survey link (i.e., a URL) in 
#'   plain text format for a specified record and data collection instrument 
#'   (and event, if longitudinal) in a project.
#'   
#' @param rcon A REDCap connection object as generated by \code{redcapConnection}.
#' @param record \code{character(1)} or \code{numeric(1)}, the record ID for 
#'   which the survey link will be downloaded.
#' @param instrument \code{character} with maximium length of 1.The unique 
#'   instrument name as seen in the second column of the Data Dictionary. 
#'   This instrument must be enabled as a survey in the project.
#' @param event \code{character} with maximum legnth of 1. the unique event 
#'   name (for longitudinal projects only).
#' @param repeat_instance \code{numeric(1)} (only for projects with repeating 
#'   instruments/events) The repeat instance number of the repeating event 
#'   (if longitudinal) or the repeating instrument (if classic or longitudinal).
#'   Default value is '1'. 
#' @param error_handling An option for how to handle errors returned by the API.
#'   see \code{\link{redcapError}}
#' @param config \code{list} Additional configuration parameters to pass to 
#'   \code{\link[httr]{POST}}. These are appended to any parameters in 
#'   \code{rcon$config}.
#' @param api_param \code{list} Additional API parameters to pass into the
#'   body of the API call. This provides users to execute calls with options
#'   that may not otherwise be supported by \code{redcapAPI}.
#'   
#' @section REDCap API Documentation:
#' This method allows you to export some of the basic attributes of a given 
#' REDCap project, such as the project's title, if it is longitudinal, if 
#' surveys are enabled, the time the project was created and moved to 
#' production, etc.
#' 
#' @section REDCap Version:
#' 5.8.2+ 
#' 
#' @section Known REDCap Limitations:
#' None.
#'
#' @author Benjamin Nutter
#'
#' @references
#' Please refer to your institution's API documentation.
#' 
#' @export

exportSurveyLink <- function(rcon, 
                             record, 
                             instrument = character(0), 
                             event = character(0),
                             repeat_instance = 1,
                             error_handling = getOption("redcap_error_handling", "error"), 
                             config = list(), 
                             api_param = list()){
  coll <- checkmate::makeAssertCollection()
  
  checkmate::assert_class(x = rcon,
                          classes = "redcapApiConnection",
                          add = coll)
  
  if (!checkmate::test_integerish(x = record, len = 1) &&
      !checkmate::test_character(x = record, len = 1)){
    coll$push("`record` must be either a `character(1)` or `integerish(1)`")
  }
  
  checkmate::assert_character(x = instrument, 
                              max.len = 1, 
                              add = coll)
  
  checkmate::assert_character(x = event, 
                              max.len = 1, 
                              add = coll)
  
  checkmate::assert_integerish(x = repeat_instance, 
                               len = 1, 
                               add = coll)
  
  error_handling <- checkmate::matchArg(x = error_handling, 
                                        choices = c("null", "error"),
                                        add = coll)
  
  checkmate::assert_list(x = config,
                         names = "named",
                         add = coll)
  
  checkmate::assert_list(x = api_param, 
                         names = "named",
                         add = coll)
  
  checkmate::reportAssertions(coll)
  
  body <-
      list(content = "surveyLink", 
           returnFormat = "csv",
           record = record,
           instrument = instrument, 
           event = event, 
           repeat_instance = repeat_instance)
  
  response <- makeApiCall(rcon, 
                          body = c(body, api_param), 
                          config = config)
  
  redcapError(response, error_handling = error_handling)
  
  rawToChar(response$content)
}

# Aliases -----------------------------------------------------------

#' @rdname exportSurveyLink
#' @export

export_survey_link <- exportSurveyLink