#' @name importArms
#' @title Import Arms To or Rename Arms In a Project
#' 
#' @description This method allows you to import Arms into a project or to 
#'   rename existing Arms in a project. To use this method, you must have API 
#'   Import/Update privileges AND Project Design/Setup privileges in the project.
#'   
#' @param rcon A REDCap connection object as generated by 
#'   \code{redcapConnection}.
#' @param arms \code{data.frame} with two columns.  By default, it is assumed
#'   that the names of these columns are \code{arm_num} and \code{name}, but
#'   these may be changed using the \code{colnames} argument. See Details for 
#'   more about how these columns are validated.
#' @param arm_num \code{character(1)} The name of the column in \code{arms}
#'   that gives the arm number.
#' #' @param arm_name \code{character(1)} The name of the column in \code{arms}
#'   that gives the arm name.
#' @param override \code{logical(1)}. When \code{FALSE}, you may only add new 
#'   or rename existing arms. When \code{TRUE}, a full overwrite is done, which 
#'   will delete all arms and replace them with the designations in the 
#'   \code{arms} argument.
#' @param error_handling An option for how to handle errors returned by the API.
#'   see \code{\link{redcapError}}
#' @param config \code{list} Additional configuration parameters to pass to 
#'   \code{\link[httr]{POST}}. These are appended to any parameters in 
#'   \code{rcon$config}.
#' @param api_param \code{list} Additional API parameters to pass into the
#'   body of the API call. This provides users to execute calls with options
#'   that may not otherwise be supported by \code{redcapAPI}.
#'   
#' @details 
#' The column representing the arm number must be either \code{character} 
#' or \code{numeric}. If it is a \code{character}, it will be coerced to 
#' a \code{numeric}. Before the import, the contents are tested and must be
#' \code{integerish}.
#' 
#' The column representing the arm name must be atomic. It will be converted 
#' to a \code{character} before the import.
#' 
#' @section REDCap API Documentation:
#' This method allows you to import Arms into a project or to rename existing 
#' Arms in a project. You may use the parameter \code{override = TRUE} as a 
#' 'delete all + import' action in order to erase all existing Arms in the 
#' project while importing new Arms. Notice: Because of the \code{override} 
#' parameter's destructive nature, this method may only use 
#' \code{override = TRUE} for projects in Development status.
#' 
#' NOTE: This only works for longitudinal projects.
#' 
#' @section REDCap Version:
#' At least 8.1.17+ (and likely some earlier versions)
#' 
#' @return 
#' None.
#' 
#' @references
#' Please refer to your institution's API documentation.
#' 
#' @export

importArms <- function(rcon, 
                       arms, 
                       arm_num = "arm_num", 
                       arm_name = "name",
                       override = FALSE, 
                       error_handling = getOption("redcap_error_handling", "error"), 
                       config = list(), 
                       api_param = list()){
  
  coll <- checkmate::makeAssertCollection()
  
  checkmate::assert_class(x = rcon, 
                          classes = "redcapApiConnection", 
                          add = coll)
  
  checkmate::assert_data_frame(x = arms, 
                               add = coll)
  
  checkmate::assert_character(x = arm_num, 
                              len = 1, 
                              add = coll)
  
  checkmate::assert_character(x = arm_name, 
                              len = 1, 
                              add = coll)
  
  checkmate::assert_logical(x = override, 
                            len = 1, 
                            add = coll)
  
  error_handling <- checkmate::matchArg(x = error_handling, 
                                        choices = c("null", "error"),
                                        add = coll)
  
  checkmate::assert_list(x = config,
                         names = "named",
                         add = coll)
  
  checkmate::assert_list(x = api_param, 
                         names = "named",
                         add = coll)
  
  checkmate::reportAssertions(coll)
 
  checkmate::assert_subset(x = c(arm_num, arm_name), 
                           choices = names(arms), 
                           add = coll)
  
  checkmate::reportAssertions(coll)

  data <- arms[c(arm_num, arm_name)]
  
  if (!checkmate::test_integerish(x = data[[arm_num]]) &&
      !checkmate::test_character(x = data[[arm_num]])){
    coll$push(sprintf("`arms$%s` must be either a `character(1)` or `integerish(1)`", 
                      colnames[1]))
  }
  
  checkmate::assert_atomic(x = data[[arm_name]], 
                           add = coll, 
                           .var.name = arm_name)
  
  checkmate::reportAssertions(coll)

  data <- dataFrameToString(data)
  
  body <- list(content = "arm",
               action = "import", 
               override = as.character(as.numeric(override)), 
               data = data, 
               format = "csv")

  response <- makeApiCall(rcon, 
                          body = c(body, api_param), 
                          config = config)
  
  redcapError(response, error_handling = error_handling)
  
  if (response$status_code == 200){
    as.numeric(as.character(response))
  }
  
}

#' @rdname importArms
#' @export

import_arms <- importArms